// <auto-generated />
using System;
using Buns.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Buns.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210608103717_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Buns.Domain.Entities.Buns.Bun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("BakeTime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BunTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ControlSaleTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("StartPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("TimeToSell")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BunTypeId");

                    b.ToTable("Buns");
                });

            modelBuilder.Entity("Buns.Domain.Entities.Buns.BunType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BunTypes");
                });

            modelBuilder.Entity("Buns.Domain.Entities.Buns.Bun", b =>
                {
                    b.HasOne("Buns.Domain.Entities.Buns.BunType", "BunType")
                        .WithMany()
                        .HasForeignKey("BunTypeId");

                    b.Navigation("BunType");
                });
#pragma warning restore 612, 618
        }
    }
}
